services:
  mongo:
    image: mongo:latest
    container_name: UserDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./docker/mongodb/:/data/db
    ports:
      - "${MONGO_PORT}:27017"
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    volumes:
      - ./docker/redis-stack/:/data
      - ./docker/redis-stack/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_INSIGHT_PORT}:8001"
    command: ["redis-server", "--protected-mode", "no"]
