services:
  mongo:
    image: mongo:latest
    container_name: UserDB
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./database/mongodb/:/data/db
    ports:
      - "${MONGO_PORT}:27017"
  redis-stack:
    image: redis/redis-stack:latest
    container_name: RedisSession
    restart: always
    volumes:
      - ./database/redis-stack/:/data
      - ./database/redis-stack/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_PORT}:6379"
      - "${REDIS_INSIGHT_PORT}:8001"
    command: ["redis-server", "--protected-mode", "no"]
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootMINIO
    command: server --console-address ":9001" /data
