services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    volumes:
      - ./docker/mongodb/:/data/db
    ports:
      - "${MONGO_PORT}:27017"
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    restart: always
    volumes:
      - ./docker/redis-stack/:/data
    ports:
      - "${REDIS_PORT}:6379" 
      - "${REDIS_INSIGHT_PORT}:8001"
  


