services:
  AuthService:
    image: auth-service
    container_name: AuthService
    hostname: ${APP_HOST}
    restart: always
    environment:
      EXPOSE_PORT: ${EXPOSE_PORT}
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      MONGO_HOST_MASTER: ${MONGO_HOST_MASTER}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      ACCESS_KEY: ${ACCESS_KEY}
      REFRESH_KEY: ${REFRESH_KEY}
      KAFKA_HOST: ${KAFKA_HOST}
      REDIS_HOST: ${REDIS_HOST}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    networks:
      - AuthNetwork
      - KafkaNetwork

  Sub-AuthService:
    image: auth-service
    container_name: SubAuthService
    hostname: ${SUB_APP_HOST}
    restart: always
    environment:
      EXPOSE_PORT: ${EXPOSE_PORT}
      APP_PORT: ${SUB_APP_PORT}
      APP_HOST: ${SUB_APP_HOST}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      MONGO_HOST_MASTER: ${MONGO_HOST_MASTER}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      ACCESS_KEY: ${ACCESS_KEY}
      REFRESH_KEY: ${REFRESH_KEY}
      KAFKA_HOST: ${KAFKA_HOST}
      REDIS_HOST: ${REDIS_HOST}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    networks:
      - AuthNetwork
      - KafkaNetwork
  nginx:
    image: nginx
    container_name: LoadBalanceAuthService
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "${EXPOSE_PORT}:80"
    networks:
      - AuthNetwork
      - KafkaNetwork
    depends_on:
      - AuthService
      - Sub-AuthService

networks:
  AuthNetwork:
    external: true
    driver: bridge
  KafkaNetwork:
    external: true
    driver: bridge
