services:
  AuthService:
    image: auth-service
    container_name: AuthService
    hostname: ${APP_HOST}
    restart: always
    environment:
      EXPOSE_PORT: ${EXPOSE_PORT}
      APP_NAME: ${APP_NAME}
      APP_PORT: ${APP_PORT}
      APP_HOST: ${APP_HOST}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      MONGO_HOST_PRIMARY: ${MONGO_HOST_PRIMARY}
      MONGO_HOST_SLAVE_1: ${MONGO_HOST_SLAVE_1}
      MONGO_HOST_SLAVE_2: ${MONGO_HOST_SLAVE_2}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      ACCESS_KEY: ${ACCESS_KEY}
      REFRESH_KEY: ${REFRESH_KEY}
      KAFKA_HOST: ${KAFKA_HOST}
      REDIS_SESSION_HOST: ${REDIS_SESSION_HOST}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      CONSUL_HOST: ${CONSUL_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - AuthNetwork
      - KafkaNetwork
      - ConSulNetwork

  Sub-AuthService:
    image: auth-service
    container_name: SubAuthService
    hostname: ${SUB_APP_HOST}
    restart: always
    environment:
      EXPOSE_PORT: ${EXPOSE_PORT}
      APP_NAME: ${SUB_APP_NAME}
      APP_PORT: ${SUB_APP_PORT}
      APP_HOST: ${SUB_APP_HOST}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      MONGO_HOST_PRIMARY: ${MONGO_HOST_PRIMARY}
      MONGO_HOST_SLAVE_1: ${MONGO_HOST_SLAVE_1}
      MONGO_HOST_SLAVE_2: ${MONGO_HOST_SLAVE_2}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      ACCESS_KEY: ${ACCESS_KEY}
      REFRESH_KEY: ${REFRESH_KEY}
      KAFKA_HOST: ${KAFKA_HOST}
      REDIS_SESSION_HOST: ${REDIS_SESSION_HOST}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      CONSUL_HOST: ${CONSUL_HOST}
    networks:
      - AuthNetwork
      - KafkaNetwork
      - ConSulNetwork

  BackUp-AuthService:
    image: auth-service
    container_name: BackUpAuthService
    hostname: ${BackUp_APP_HOST}
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      EXPOSE_PORT: ${EXPOSE_PORT}
      APP_NAME: ${BackUp_APP_NAME}
      APP_PORT: ${BackUp_APP_PORT}
      APP_HOST: ${BackUp_APP_HOST}
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
      MONGO_HOST_PRIMARY: ${MONGO_HOST_PRIMARY}
      MONGO_HOST_SLAVE_1: ${MONGO_HOST_SLAVE_1}
      MONGO_HOST_SLAVE_2: ${MONGO_HOST_SLAVE_2}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_DATABASE: ${MONGO_DATABASE}
      ACCESS_KEY: ${ACCESS_KEY}
      REFRESH_KEY: ${REFRESH_KEY}
      KAFKA_HOST: ${KAFKA_HOST}
      REDIS_SESSION_HOST: ${REDIS_SESSION_HOST}
      MINIO_HOST: ${MINIO_HOST}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      CONSUL_HOST: ${CONSUL_HOST}
    networks:
      - AuthNetwork
      - KafkaNetwork
      - ConSulNetwork
  nginx:
    image: nginx
    container_name: LoadBalanceAuthService
    hostname: nginx.event
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./nginx/localhost.key:/etc/ssl/private/localhost.key
    ports:
      - "${EXPOSE_PORT}:443"
    networks:
      - AuthNetwork
    depends_on:
      - AuthService
      - Sub-AuthService
      - BackUp-AuthService

networks:
  AuthNetwork:
    external: true
    driver: bridge
  KafkaNetwork:
    external: true
    driver: bridge
  ConSulNetwork:
    external: true
    driver: bridge
