APP_NAME = process.env.APP_NAME;
APP_PORT = process.env.APP_PORT;
APP_HOST = process.env.APP_HOST;
EXPOSE_DOMAIN = process.env.EXPOSE_DOMAIN;
EXPOSE_HOST = process.env.EXPOSE_HOST || "127.0.0.1";
EXPOSE_PORT = process.env.EXPOSE_PORT;
EMAIL = process.env.EMAIL;
EMAIL_PASSWORD = process.env.EMAIL_PASSWORD;
MONGO_HOST_PRIMARY = process.env.MONGO_HOST_PRIMARY;
MONGO_HOST_SECONDARY_1 = process.env.MONGO_HOST_SECONDARY_1;
MONGO_HOST_SECONDARY_2 = process.env.MONGO_HOST_SECONDARY_2;
MONGO_PORT = process.env.MONGO_PORT_MASTER || 27017;
MONGO_USERNAME = process.env.MONGO_USERNAME;
MONGO_PASSWORD = process.env.MONGO_PASSWORD;
MONGO_DATABASE = process.env.MONGO_DATABASE;
REDIS_SESSION_HOST = process.env.REDIS_SESSION_HOST;
REDIS_PORT = +process.env.REDIS_PORT || 6379;
REDIS_PASSWORD = process.env.REDIS_PASSWORD;
KAFKA_HOST = process.env.KAFKA_HOST;
KAFKA_PORT = process.env.KAFKA_PORT || 19092;
ACCESS_KEY = process.env.ACCESS_KEY;
REFRESH_KEY = process.env.REFRESH_KEY;
MINIO_HOST = process.env.MINIO_HOST || 9000;
MINIO_ACCESS_KEY = process.env.MINIO_ACCESS_KEY;
MINIO_SECRET_KEY = process.env.MINIO_SECRET_KEY;
CONSUL_HOST = process.env.CONSUL_HOST;
module.exports = {
  CONSUL_HOST,
  EXPOSE_DOMAIN,
  APP_NAME,
  APP_PORT,
  APP_HOST,
  EXPOSE_HOST,
  EXPOSE_PORT,
  MONGO_HOST_PRIMARY,
  MONGO_HOST_SECONDARY_1,
  MONGO_HOST_SECONDARY_2,
  EMAIL,
  EMAIL_PASSWORD,
  MONGO_PORT,
  MONGO_USERNAME,
  MONGO_PASSWORD,
  MONGO_DATABASE,
  REDIS_SESSION_HOST,
  REDIS_PORT,
  REDIS_PASSWORD,
  ACCESS_KEY,
  REFRESH_KEY,
  KAFKA_HOST,
  KAFKA_PORT,
  MINIO_HOST,
  MINIO_ACCESS_KEY,
  MINIO_SECRET_KEY,
};
